# Generated by Django 3.1.11 on 2021-05-13 17:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0022_offer_meta'),
        ('vendorpromo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promo',
            name='offer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='promo', to='vendor.offer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promo',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='last updated'),
        ),
    ]
