# Generated by Django 3.2.19 on 2023-05-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorpromo', '0003_auto_20230524_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='type',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Type'),
        ),
    ]
