# Generated by Django 3.2.19 on 2023-05-31 20:08

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorpromo', '0004_affiliate_name_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='code',
            field=autoslug.fields.AutoSlugField(blank=True, null=True, sep='copy', unique_with=('promo__site',), verbose_name='Affiliate Code'),
        ),
    ]
