from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.http.response import HttpResponseNotFound
from django.shortcuts import redirect
from django.utils.translation import ugettext as _
from django.views import View

from vendor.views.vendor import AddToCartView

from vendorpromo.processors import PromoProcessor
from vendorpromo.models import Promo


promo_processor = PromoProcessor


class ValidateCodeCheckoutProcessAPIView(LoginRequiredMixin, View):
    """
    When a customer is applying a code during the checkout process
    the function will check if the entered code is valid to the items
    in the cart. If valsid it will swap the Offer with the Offer that
    has that promo code. If not it will display an error message.
    In both cases it will redirect to the view that called the
    endpoint.
    """
    def post(self, request, *args, **kwargs):
        # get Invoice instance
        # get Promo instance
        # loop through offers in invoice to see if any match the product form the Promo.offer instance
        ## if yes keep that invoice.offer
        ## if no return msg error.
        # initialize configured PromoProcessor
        # validate code and redeem code through processor
        ## if invalid return msg error.
        # call invoice.swap(original_offer, promo.offer)
        return redirect(request.META.get('HTTP_REFERER', "vendor:cart"))


class ValidateLinkCodeAPIView(AddToCartView):
    """
    Endpoint used when a customer clicks on a link that has a promo code.
    The endpoint will validate the promo code and if valid it will add the
    corresponding offer to the cart. If invalid it will display a error
    message. In both case it will redirect to the cart view.
    params:
    code: string Promo Code
    site: int
    email: string optional for email additional validation
    return:
    redirect to cart.
    """
    def post(self, request, *args, **kwargs):
        # Should code be unique to sites, I am guessing yes. 
        try:
            promo = Promo.objects.get(code=request.POST.get('code'))
        except ObjectDoesNotExist:
            return HttpResponseNotFound(_("Invalid Promo Code"))
        # get Promo instance
        # check if site and promo.offer.site are the same
        # initialize configured PromoProcessor
        # validate code and redeem code through processor
        ## if invalid return msg error.
        # call redirect to vendor.views.vendor.AddToCartView (Which will redirect to the cart view)
        self.kwargs['slug'] = promo.offer.slug
        return super().post(request, args, kwargs)
# Generated by Django 3.1.11 on 2021-05-14 00:57

# import autoslug.fields
# from django.db import migrations, models
# import django.db.models.deletion
# import uuid


# class Migration(migrations.Migration):

#     initial = True

#     dependencies = [
#         ('vendor', '0022_offer_meta'),
#     ]

#     operations = [
#         migrations.CreateModel(
#             name='Promo',
#             fields=[
#                 ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
#                 ('updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
#                 ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
#                 ('name', models.CharField(max_length=80, verbose_name='Promo Name')),
#                 ('description', models.TextField(blank=True, default=None, help_text='Enter a description for your Promo Code', null=True, verbose_name='Promo Description')),
#                 ('code', models.CharField(max_length=80, verbose_name='Code')),
#                 ('campaign_id', models.CharField(blank=True, max_length=80, null=True, verbose_name='Campaign Identifier')),
#                 ('campaign_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Campaign Name')),
#                 ('campaign_description', models.TextField(blank=True, null=True, verbose_name='Campaign Description')),
#                 ('meta', models.JSONField(blank=True, default=dict, null=True, verbose_name='Meta')),
#                 ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=('offer__site__id',))),
#                 ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo', to='vendor.offer')),
#             ],
#             options={
#                 'verbose_name': 'Promo',
#                 'verbose_name_plural': 'Promos',
#             },
#         ),
#     ]



